# Generated by Django 3.1.6 on 2021-02-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presionarterial',
            old_name='presion_diatolica_mañana',
            new_name='presion_diastolica_mañana',
        ),
        migrations.RenameField(
            model_name='presionarterial',
            old_name='presion_diatolica_tarde',
            new_name='presion_diastolica_tarde',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='nombre',
        ),
    ]
